# Generated by Django 4.2.1 on 2023-07-03 03:57

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userapp", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nomi")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Holati")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hizmat",
                "verbose_name_plural": "Hizmatlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Worker_Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Miqdori"
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Holati")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishchi un to'lov",
                "verbose_name_plural": "Ishchi un to'lovlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("yan", "Yanvar"),
                            ("fev", "Fevral"),
                            ("mar", "Mart"),
                            ("apr", "Aprel"),
                            ("may", "May"),
                            ("iyn", "Iyun"),
                            ("iyl", "Iyul"),
                            ("avg", "Avgust"),
                            ("sen", "Sen"),
                            ("okt", "Oktyabr"),
                            ("noy", "Noyabr"),
                            ("dek", "Dekabr"),
                        ],
                        max_length=25,
                        verbose_name="Oylar",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("amount", models.PositiveIntegerField(verbose_name="Miqdori")),
                ("status", models.BooleanField(default=True, verbose_name="Holati")),
                ("created_at", models.DateTimeField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="mainapp.branch",
                        verbose_name="Filial",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="mainapp.group",
                        verbose_name="gruhi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="userapp.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nomi")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yan", "Yanvar"),
                            ("fev", "Fevral"),
                            ("mar", "Mart"),
                            ("apr", "Aprel"),
                            ("may", "May"),
                            ("iyn", "Iyun"),
                            ("iyl", "Iyul"),
                            ("avg", "Avgust"),
                            ("sen", "Sen"),
                            ("okt", "Oktyabr"),
                            ("noy", "Noyabr"),
                            ("dek", "Dekabr"),
                        ],
                        default="yan",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Miqdori"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Izoh")),
                ("status", models.BooleanField(default=True, verbose_name="Holati")),
                ("created_at", models.DateTimeField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoms",
                        to="finance.area",
                        verbose_name="Xizmat turi",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoms",
                        to="mainapp.branch",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daromad",
                "verbose_name_plural": "Daromadlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Harajat nomi")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Miqdori"
                    ),
                ),
                ("comment", models.TextField(verbose_name="Izoh")),
                ("status", models.BooleanField(default=True, verbose_name="Holati")),
                ("created_at", models.DateTimeField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="mainapp.branch",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harajat",
                "verbose_name_plural": "Harajatlar",
                "ordering": ("-created_at",),
            },
        ),
    ]
