# Generated by Django 4.2.1 on 2023-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
